version: '3'

services:
  app:
    environment:
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - LTI_KEY=${LTI_KEY}
      - LTI_SECRET=${LTI_SECRET}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  redis:
    image: redis:5.0.3-alpine
    restart: always
  worker:
    build: 
      context: ./redis-worker
      dockerfile: Dockerfile-redis-worker
    depends_on:
      - redis
    links:
      - redis

  mysql:
    image: mysql:5.7.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
